jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      run: mvn -B install --no-transfer-progress
    strategy:
      matrix:
        java-version:
        - 8
        - 8.0.192
        - 11
        - 11.0.3
        - 17
        - 17.0.0+35
  coverage:
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 17
    - continue-on-error: true
      run: mvn -B verify --no-transfer-progress
    - continue-on-error: true
      uses: codecov/codecov-action@v3
      with:
        file: ./**/target/site/jacoco/jacoco.xml
        name: codecov
name: build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
